### ISSUE TITLE
Could not sign the transaction

### ISSUE THREAD

**Issue by otta88sun** [coinspark/php-OP_RETURN#3]
I get this error in return of OP_RETURN_send().
I checked all parameters, them are ok.
Configurations in op_return.php is ok, i just changed the max OP return size to 80 and define('OP_RETURN_BTC_FEE', $site['fee']); where $site['fee'] is a float number.

**Comment by gidgreen** [comment]
What happens if you leave both these parameters on their original details?

**Comment by otta88sun** [comment]
Same error, i'm thinking about the float number. There are 0.0001 value, and maybe php could see them like 1E- 5 and generate error but i am not sure

**Comment by otta88sun** [comment]
The data i'm passing to function is somethink like "Our stories begin..." and should be UTF8 format, I really can't understand what generate this error.

**Comment by otta88sun** [comment]
I got it maybe.
My wallet is protected by password, is locked...

**Comment by otta88sun** [comment]
Confirm. By wallet was locked, so unable to sign tx.
Nice work gidgreen

**Comment by gidgreen** [comment]
Thanks - that indeed explains it!
