### ISSUE TITLE
Differences between op_return_send and op_return_store

### ISSUE THREAD

**Issue by otta88sun** [coinspark/php-OP_RETURN#4]
What are the differences between op_return_send and op_return_store?

In the first one i send a transaction to an address with custom op_return,

in the second one, how can it store info withouth doing a tx?
Why in the return there are more tx ids?

Thank you.

**Comment by gidgreen** [comment]
OP_RETURN_store() is for storing larger pieces of information that won't fit in the metadata of a single transaction. It builds a chain of transactions instead.

**Comment by otta88sun** [comment]
Really fine idea, but the address for transactions are keep from the wallet like with a getnewaddress()?

**Comment by gidgreen** [comment]
OP_RETURN_store() uses getrawchangeaddress to determine the address to send the transaction to.

**Comment by otta88sun** [comment]
Nice explanations! Thank you!
